### ISSUE TITLE
PCMFitMixed

### ISSUE THREAD

**Issue by tvdooren** [venelin/PCMFit#1]
I am trying to run the models without PCMBaseCpp, on a Windows 7 machine with R 3.6.1. PCMFit works. When I call PCMFitMixed, the first messages returned are 
"Calling generatePCMModelsFun()...
Error in file(con, "rb") : cannot open the connection
In addition: Warning message:
In file(con, "rb") :
  cannot open file 'DefineParameterLimits.R': No such file or directory"

**Comment by venelin** [comment]
The file DefineParameterLimits.R within the vignettes directory was .gitignored. I've now added this file. Please, git pull and retry.

**Comment by venelin** [comment]
I'm closing this issue about the missing file now. If needed, feel free to re-open it or open a new one.
