### ISSUE TITLE
Data length warning message

### ISSUE THREAD

**Issue by mark-grabowski** [venelin/PCMFit#4]
I'm was trying to use PCMFitMixed if for 2 different analyses and one thing that kept happening is I got this Warning message after it completes a run:

2: In matrix(P$mean[i[iP]], nrow = n, ncol = length(iP),  ... :
data length exceeds size of matrix
3: In matrix(P$mean[i[iP]], nrow = n, ncol = length(iP),  ... :
data length exceeds size of matrix

Though my data set was originally a matrix, It seems like I solved this issue (no more warning messages) by converting my data set to a matrix using the following step, which removes all the row and column names:

```
X<-matrix(as.numeric(X),nrow=dim(X)[1],ncol=dim(X)[2])

```

**Comment by venelin** [comment]
Hello, that looks strange, but I cannot locate the code generating this Warning.
