### ISSUE TITLE
Error in logLik.PCM(X[[i]], ...)

### ISSUE THREAD

**Issue by Sunkuo-1212** [venelin/PCMFit#7]
I  ran PCMFitMixed() successfully, but  there was an error message when I  summary the result(dtsummary):
```
Error in logLik.PCM(X[[i]], ...) : 
  logLik.PCM:: When calling logLik.PCM on a model object, it should have a k x N numeric matrix a

ttribute called 'X'.
```
The problem occurred at  `sapply(listModels, logLik)`. This  error message confused me for a long time. So I uploaded my code and file for your help. 
[PCMfitMixed.zip](https://github.com/venelin/PCMFit/files/5305212/PCMfitMixed.zip)

**Comment by venelin** [comment]
This was indeed a bug happening in the special case of a single trait. I've fixed it. Please, pull/reinstall the PCMFit package and try your code again. Please, close the issue if the problem got solved.

**Comment by Sunkuo-1212** [comment]
The issue has been resolved! Thank you very much!
